SmartCar/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'SmartCar.views.index',name='home'),
    url(r'^about/$', 'SmartCar.views.about',name='about'),
    url(r'^manage/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^post/', include('post.urls')),
    url(r'^discuss/',include('discuss.urls')),
)

discuss/urls.py
from django.conf.urls import patterns,include, url

urlpatterns = patterns('discuss.views',
    url(r'^$','index',name='discuss_index'),
    url(r'^(?P<num>[0-9]+)/$','detail'),
)

post/urls.py
from django.conf.urls import patterns,include, url

urlpatterns = patterns('post.views',
    url(r'^$','index',name='post_index'),
    url(r'^(?P<num>[0-9]+)/$','detail'),
)

team/urls.py
from django.conf.urls import patterns,include, url

urlpatterns = patterns('team.views',
    url(r'^$','index',name='team_index'),
    #url(r'^(?P<num>[\w]+)/$','detail'),
)

accounts/models.py
# encoding: utf-8

from django.db import models
from django.contrib.auth.models import User
from accounts.settings import GENDER_CHOICES, DEPARTMENT_CHOICES

#用户激活码，激活后删除
class ActivationCode(models.Model):
    user = models.OneToOneField(User,unique=True,verbose_name='用户')
    activation_code = models.CharField('激活码',max_length=40)
    mail_sent_or_not = models.BooleanField('是否已发送验证邮件',default=False)

    class Meta:
        verbose_name='激活码'
        verbose_name_plural='激活码'

    def __str__(self):
        return self.user.username


#用户信息
class MyProfile(models.Model):
    user = models.OneToOneField(User,unique=True,verbose_name='用户')
    #team = models.ForeignField(verbose_name=('队伍'))
    real_name = models.CharField('姓名',max_length=10)
    mobile = models.CharField('手机', max_length=11)
    gender = models.CharField('性别', max_length=1, choices=GENDER_CHOICES, default='M')
    department = models.CharField('院系',max_length=1,choices=DEPARTMENT_CHOICES, default='a')
    class_name = models.CharField('班级',max_length=6)
    dormitory = models.CharField('宿舍',max_length=12)

    class Meta:
        verbose_name = "用户资料"
        verbose_name_plural = "用户资料"

    def __unicode__(self):
        return self.real_name


accounts/forms.py
# encoding: utf-8

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from accounts.utils import send_activation_email, new_activation_code
from accounts.models import ActivationCode, MyProfile

from accounts.settings import GENDER_CHOICES, DEPARTMENT_CHOICES

#登陆表单
class signin_form(AuthenticationForm):
    username = forms.RegexField(label="用户名",regex=r'^[a-z0-9-]{3,16}$',
        error_messages={'required':'啊，用户名被吃掉了！','invalid':'用户名不对哦！'})

    password = forms.RegexField(label="密码", widget=forms.PasswordInput,regex=r'^[a-zA-Z0-9-_]{6,18}$',
        error_messages={'required':'啊，密码被吃掉了！','invalid':'密码不对哦！'})

    error_messages = {
        'invalid_login': "咦？用户名或密码不对哦……",
        'no_cookies': "您的浏览器不支持cookies哦……",
        'inactive': "您的账号未激活，已重新发送激活邮件，请查收……",
        'send_mail_fail': "您的账号未激活，而且发送激活邮件失败，请联系管理员以解决问题……",
        }

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username,
                password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'])
            elif not self.user_cache.is_active:
                activation_cache=ActivationCode.objects.get(user=self.user_cache).activation_code
                if send_activation_email(email=self.user_cache.email,username=self.user_cache.username,code=activation_cache):
                    raise forms.ValidationError(self.error_messages['inactive'])
                else:
                    raise forms.ValidationError(self.error_messages['send_mail_fail'])
        self.check_for_test_cookie()
        return self.cleaned_data


#注册表单
class signup_form(forms.Form):
    username = forms.RegexField(label="用户名",regex=r'^[a-z0-9-]{3,16}$',
        help_text='用户名只能由数字，小写字母，和短横组成，而且需在3-16位',
        error_messages={'required':'啊，用户名被吃掉了！','invalid':'请按右边的要求填写哦!'})

    email = forms.EmailField(label="邮箱",
        help_text='请输入可用的邮箱地址',
        error_messages={'required':'啊，邮箱地址被吃掉了！','invalid':'这个真的是邮箱地址吗？'})

    password1 = forms.RegexField(label="密码", widget=forms.PasswordInput,regex=r'^[a-zA-Z0-9-_]{6,18}$',
        help_text='密码只能由数字，大小写字母，短横和下划线组成，而且需在6-18位',
        error_messages={'required':'啊，密码被吃掉了！','invalid':'请按右边的要求填写哦!'})

    password2 = forms.RegexField(label="确认密码", widget=forms.PasswordInput,regex=r'^[a-zA-Z0-9-_]{6,18}$',
        help_text='请再次输入密码以确认',
        error_messages={'required':'啊，密码被吃掉了！','invalid':'请按右边的要求填写哦!'})


    error_messages = {
        'duplicate_username': "已经有人抢先注册这个名字了哦……",
        'duplicate_email': "咦？这个邮箱地址已经被注册过了哦……",
        'password_mismatch': "咦？两个密码怎么不一样呢？",
        'send_mail_fail': "注册成功,但是未能发送激活邮件，请联系管理员以解决问题……",
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email):
            raise forms.ValidationError(self.error_messages['duplicate_email'])
        return email

    def clean(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 != password2:
            raise forms.ValidationError(self.error_messages['password_mismatch'])

        new_user=User.objects.create_user(username,email,password1)
        new_user.is_active=False
        new_user.save()

        activation_code=new_activation_code()
        activation_cache=ActivationCode.objects.create(user=new_user,activation_code=activation_code)

        if send_activation_email(email=email,username=username,code=activation_code):
            activation_cache.mail_sent_or_not=True
            activation_cache.save()
        else:
            raise forms.ValidationError(self.error_messages['send_mail_fail'])

        return self.cleaned_data




#激活表单（填写详细资料）
class confirm_form(forms.Form):
    real_name=forms.RegexField(label='姓名',regex=u'^[\u4e00-\u9fa5]{2,6}$',
        help_text='请输入您的真实姓名',
        error_messages={'required':'需要真实姓名哦!','invalid':'这真的是您的姓名吗？'})
    mobile = forms.RegexField(label='手机',regex=r'^1(\d{10})$',
        help_text='请输入您的手机号码',
        error_messages={'required':'需要手机号哦!','invalid':'这真的是手机号吗？'})
    gender = forms.ChoiceField(label='性别',choices=GENDER_CHOICES)
    department = forms.ChoiceField(label='院系',choices=DEPARTMENT_CHOICES)
    class_name = forms.RegexField(label='班级',regex=u'^[\u4e00-\u9fa5]{1,3}\d{1,2}$',
        help_text='请输入您的班级(格式为1~3个中文字符+1~2个数字)例:工物22',
        error_messages={'required':'需要填写班级哦!','invalid':'请按右边的要求填写哦!'})
    dormitory = forms.RegexField(label='宿舍',regex=r'^ZJ(\d{1,2})#(\d{3,4})([AB]?)$',
        help_text='请输入您的宿舍地址(格式为ZJ+楼号(1-2位的数字)+#+宿舍号(3-4位的数字)(+A/B))例:ZJ10#107A',
        error_messages={'required':'需要填写宿舍地址哦!','invalid':'请按右边的要求填写哦!'})

    def sav(self,user):
        real_name = self.cleaned_data.get('real_name')
        mobile = self.cleaned_data.get('mobile')
        gender = self.cleaned_data.get('gender')
        department = self.cleaned_data.get('department')
        class_name = self.cleaned_data.get('class_name')
        dormitory = self.cleaned_data.get('dormitory')

        new_profile=MyProfile.objects.create(user=user,real_name=real_name,mobile=mobile,
            gender=gender,department=department,class_name=class_name,dormitory=dormitory)
        return new_profile

accounts/views.py
# encoding: utf-8

import urlparse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth

from accounts.forms import signin_form, signup_form, confirm_form
from accounts.models import ActivationCode
from SmartCar.settings import LOGIN_REDIRECT_URL,SIGNUP_ACCESS


#登陆
def signin(request):
    redirect_to = request.REQUEST.get('next', '')
    if request.user.is_authenticated():
        return redirect('/')
    elif request.method == 'POST':
        form=signin_form(data=request.POST)
        if form.is_valid():
            netloc = urlparse.urlparse(redirect_to)[1]
            if not redirect_to:
                redirect_to = LOGIN_REDIRECT_URL
            elif netloc and netloc != request.get_host():
                redirect_to = LOGIN_REDIRECT_URL

            auth.login(request, form.get_user())

            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            return redirect(redirect_to)
    else:
        form=signin_form()
        request.session.set_test_cookie()

    return render(request, 'accounts/signin.html',{'form':form,'next':redirect_to})

#注销
def signout(request):
    auth.logout(request)
    return redirect('/')

#注册
def signup(request):
    if request.user.is_authenticated():
        return redirect('/')
    elif not SIGNUP_ACCESS:
        return render(request,'accounts/signup_end.html')
    elif request.method == 'POST':
        form=signup_form(data=request.POST)
        if form.is_valid():
            return render(request, 'accounts/sendmail_succeed.html',{'form':form})
    else:
        form=signup_form()

    return render(request,'accounts/signup.html',{'form':form})


def confirm(request,code=None):
    if request.user.is_authenticated():
        return redirect('/')
    else:
        try:
            activation_cache=ActivationCode.objects.get(activation_code=code)
        except ActivationCode.DoesNotExist:
            return render(request,'accounts/confirm_invalid.html')

        if request.method == 'POST':
            form=confirm_form(data=request.POST)
            if form.is_valid():
                form.sav(user=activation_cache.user)
                activation_cache.user.is_active=True
                activation_cache.user.save()
                activation_cache.delete()
                return render(request,'accounts/confirm_succeed.html')
        else:
            form = confirm_form

        return render(request,'accounts/confirm.html',{'form':form})




templates/accounts/base.html
{% extends 'base.html' %}

{% block extrafooter %}
    <script type="text/javascript">
        $('#home').removeClass('active');
    </script>
    {% block extrascript %}{% endblock %}
{% endblock %}

templates/accounts/confirm.html
{% extends 'accounts/base.html' %}

{% block title %}激活{% endblock %}


{% block content %}
    <div class="sign-form-container">
        <div class="hero-unit sign-form">
            <h2 class="title">请补全信息</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-row" title="{{ form.real_name.help_text }}">
                    <label for="id_real_name" class="required">{{ form.real_name.label }}</label>{{ form.real_name }} {{ form.real_name.errors }}
                </div>
                <div class="form-row" title="{{ form.mobile.help_text }}">
                    <label for="id_mobile" class="required">{{ form.mobile.label }}</label>{{ form.mobile }} {{ form.mobile.errors }}
                </div>
                <div class="form-row">
                    <label for="" class="required">{{ form.gender.label }}</label>{{ form.gender }} {{ form.gender.errors }}
                </div>
                <div class="form-row">
                    <label for="" class="required">{{ form.department.label }}</label>{{ form.department }} {{ form.department.errors }}
                </div>
                <div class="form-row" title="{{ form.class_name.help_text }}">
                    <label for="id_class_name" class="required">{{ form.class_name.label }}</label>{{ form.class_name }} {{ form.class_name.errors }}
                </div>
                <div class="form-row" title="{{ form.dormitory.help_text }}">
                    <label for="id_dormitory" class="required">{{ form.dormitory.label }}</label>{{ form.dormitory }} {{ form.dormitory.errors }}
                </div>
                <div class="submit-row">
                    <input type="submit" value="登陆" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block extrascript %}
    <script type="text/javascript">
        $('#id_real_name').focus();
        $('.form-row').tooltip({delay: { show: 300, hide: 300 },placement:'right'});
    </script>
{% endblock %}

templates/accounts/confirm_invalid.html
{% extends 'accounts/base.html' %}

{% block title %}激活失败{% endblock %}

{% block content_title %}
    <h1>激活失败</h1>
    <hr />
{% endblock %}

{% block content %}
    <p>对不起,该激活码不存在……</p>
{% endblock %}

templates/accounts/confirm_message.html
<!DOCTYPE HTML>
<html>
<head>
    <title>Email 地址验证</title>
</head>
<body>
Email 地址验证
<br/>
<p>亲爱的{{ username }}，<br>这封信是由<strong>{{ org }}</strong>发送的。</p>
<p>您收到这封邮件，是由于在<strong>{{ site_name }}</strong>进行了新用户注册，
    或用户修改 Email 使用了这个邮箱地址。如果您并没有访问过<strong>{{ site_name }}</strong>，
    或没有进行上述操作，请忽略这封邮件。您不需要退订或进行其他进一步的操作。</p>
<br/>
----------------------------------------------------------------------
<br/>
<strong>帐号激活说明</strong>
<br/>
----------------------------------------------------------------------
<br/>
<br/>
<p>如果新注册了<strong>{{ site_name }}</strong>，或在修改您的注册 Email 时使用了本地址，
    我们需要对您的地址有效性进行验证以避免垃圾邮件或地址被滥用。</p>
<p>您只需点击下面的链接即可完成注册步骤激活您的帐号：
    <br/>
    <a href="http://car.thudep.org/accounts/confirm/{{ confirm_code }}/">http://car.thudep.org/accounts/confirm/{{ confirm_code }}/</a>
    <br/>
    (如果上面不是链接形式，请将该地址手工粘贴到浏览器地址栏再访问)</p>
<p>感谢您的访问，祝您使用愉快！</p>
<p>此致
    <br/>
    <strong>{{ org }}</strong>.
    <br/>
    http://car.thudep.org/</p>
</body>
</html>

templates/accounts/confirm_succeed.html
{% extends 'accounts/base.html' %}

{% block title %}激活成功{% endblock %}

{% block content_title %}
    <h1>激活成功</h1>
    <hr />
{% endblock %}

{% block content %}
    <p>现在您可以使用注册的账号登陆网站了……</p>
{% endblock %}

templates/accounts/sendmail_succeed.html
{% extends 'accounts/base.html' %}

{% block title %}注册成功{% endblock %}

{% block content_title %}
    <h1>注册成功</h1>
    <hr />
{% endblock %}

{% block content %}
    <p>您已成功注册，请查收激活邮件，按步骤激活。</p>
{% endblock %}

templates/accounts/signin.html
{% extends 'accounts/base.html' %}

{% block title %}登陆{% endblock %}

{% block content %}
<div class="sign-form-container">
    <div class="hero-unit sign-form">
        <h2 class="title">登陆</h2>
        <form action="{% url signin %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-row">
                <label for="id_username" class="required">{{ form.username.label }}</label>{{ form.username }} {{ form.username.errors }}
            </div>
            <div class="form-row">
                <label for="id_password" class="required">{{ form.password.label }}</label>{{ form.password }} {{ form.password.errors }}
                <input type="hidden" name="next" value="{{ next }}" />
            </div>
            <div class="submit-row">
                <input type="submit" value="登陆" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block extrascript %}
    <script type="text/javascript">
        $('#id_username').focus();
    </script>
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block title %}注册{% endblock %}

{% block content %}
    <div class="sign-form-container">
        <div class="hero-unit sign-form">
            <h2 class="title">注册</h2>
            <form action="{% url signup %}" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-row" title="{{ form.username.help_text }}">
                    <label for="id_username" class="required">{{ form.username.label }}</label>{{ form.username }} {{ form.username.errors }}
                </div>
                <div class="form-row" title="{{ form.email.help_text }}">
                    <label for="id_email" class="required">{{ form.email.label }}</label>{{ form.email }} {{ form.email.errors }}
                </div>
                <div class="form-row" title="{{ form.password1.help_text }}">
                    <label for="id_password1" class="required">{{ form.password1.label }}</label>{{ form.password1 }} {{ form.password1.errors }}
                </div>
                <div class="form-row" title="{{ form.password2.help_text }}">
                    <label for="id_password2" class="required">{{ form.password2.label }}</label>{{ form.password2 }} {{ form.password2.errors }}
                </div>
                <div class="submit-row">
                    <input type="submit" value="提交" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block extrascript %}
    <script type="text/javascript">
        $('#id_username').focus();
        $('.form-row').tooltip({delay: { show: 300, hide: 300 },placement:'right'});
    </script>
{% endblock %}

templates/accounts/signup_end.html
{% extends 'accounts/base.html' %}

{% block title %}报名结束{% endblock %}

{% block content_title %}
    <h1>报名结束</h1>
    <hr />
{% endblock %}

{% block content %}
    <p>啊咧？报名结束了哦……</p>
{% endblock %}